-- CBREED 테이블 더미 데이터
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(10,'Ragdoll');  -- 랙돌
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(20,'RussianBlue');  -- 러시안 블루 
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(30,'Munchkin');  -- 먼치킨
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(40,'Bengal');  --  뱅갈
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(50,'SiameseCat');  --  샴(샤미즈)
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(60,'Sphynx');  -- 스핑크스
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(70,'PersianCat');  -- 페르시안
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(80,'Abyssinian');  -- 아비시니안
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(90,'TurkishAngora');  -- 터키시앙고라
INSERT INTO CBREED ( CBREEDNO, CBREEDNAME)
    VALUES(100,'ScottishFold');  --  스코티시 폴드
    
SELECT * FROM CBREED ORDER BY CBREEDNO;

SELECT * FROM CBREED;