DROP SEQUENCE CZIM_SEQ;

DROP TABLE CZIM;

CREATE SEQUENCE CZIM_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;

CREATE TABLE CZIM(
    ZNO         NUMBER(6) PRIMARY KEY,
    MID         REFERENCES MEMBER(MID),
    CNUM        REFERENCES CAT(CNUM),
    ZDATE       DATE DEFAULT SYSDATE NOT NULL
);


-- 찜 하기
INSERT INTO CZIM(ZNO, MID, CNUM ) VALUES (CZIM_SEQ.NEXTVAL,'aaa', '7');
-- select count(*) from 찜 테이블 where mid = sessionid and wno='1';
-- 찜 눌렀는지 안눌렀는지 여부 
SELECT COUNT(*) FROM CZIM WHERE MID='aaa' AND CNUM=7;

-- 찜 취소 
DELETE FROM CZIM WHERE MID='aaa' AND CNUM=7;
ROLLBACK;
-- 내가 찜한 리스트 
SELECT CNUM, CNAME, CIMAGE1, CBREEDNAME FROM (SELECT * FROM CAT C, CBREED CB WHERE C.CBREEDNO = CB.CBREEDNO)
    WHERE CNUM IN (SELECT CNUM FROM CZIM WHERE MID='aaa') ;