-- DBREED 테이블 더미데이터
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(10,'GoldenRetriever');  -- 골든 리트리버
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(20,'Maltese');   -- 말티즈
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(30,'BichonFrise');  -- 비숑 프리제
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(40,'Beagle');   -- 비글
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(50,'ShihTzu');  -- 시츄
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(60,'Chihuahua');  -- 치와와
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(70,'Pomeranian');  -- 포메라니안
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(80,'WelshCorgi');  -- 웰시코기
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(90,'JindoDog');  -- 진돗개
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(100,'Pug');   -- 퍼그
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(110,'Poodle');   -- 푸들
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(120,'ShibaInu');  -- 시바 이누
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(130,'Dachshund');  -- 닥스훈트
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(140,'Samoyed');  -- 사모예드
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(150,'SiberianHusky');  -- 시베리안 허스키
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(160,'BorderCollie');  -- 보더콜리
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(170,'PoongsanDog');  -- 풍산개
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(180,'YorkshireTerrier');  -- 요크셔 테리어
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(190,'FrenchBulldog');  -- 프렌치 불도그
INSERT INTO DBREED ( DBREEDNO, DBREEDNAME)
    VALUES(200,'Dobermann');     -- 도베르만 
    

    
    
SELECT * FROM DBREED ORDER BY DBREEDNO;


COMMIT;