-- 자유 게시판
DROP SEQUENCE FREE_SEQ;

CREATE SEQUENCE FREE_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

DROP TABLE FREEBOARD;

CREATE TABLE FREEBOARD(
    FNUM NUMBER(6) PRIMARY KEY,
    MID REFERENCES MEMBER(MID) NOT NULL,
    FTITLE VARCHAR2(30) NOT NULL,
    FCONTENT VARCHAR2(3000) NOT NULL,
    FRDATE DATE DEFAULT SYSDATE NOT NULL,
    FFHIT NUMBER(6) DEFAULT 0 NOT NULL,
    FGROUP NUMBER(6) NOT NULL,
    FSTEP NUMBER(6) NOT NULL,
    FINDENT NUMBER(6) NOT NULL,
    FIP VARCHAR2(50) NOT NULL,
    FFILENAME1 VARCHAR2(50),
    FFILENAME2 VARCHAR2(50),
    FFILENAME3 VARCHAR2(50)
);