-- 자유 게시판
DROP SEQUENCE FREE_SEQ;

CREATE SEQUENCE FREE_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;

DROP TABLE FREEBOARD;

CREATE TABLE FREEBOARD(
    FNUM NUMBER(6) PRIMARY KEY,  -- 글 번호
    MID REFERENCES MEMBER(MID) NOT NULL,  -- 작성자 아이디
    FTITLE VARCHAR2(100) NOT NULL,   -- 제목
    FCONTENT VARCHAR2(3000) NOT NULL,  -- 본문
    FRDATE DATE DEFAULT SYSDATE NOT NULL,  -- 작성시점 
    FHIT NUMBER(6) DEFAULT 0 NOT NULL,  -- 조회수
    FGROUP NUMBER(6) NOT NULL,   -- 글 그룹
    FSTEP NUMBER(6) NOT NULL,  -- 그룹내 출력 순서
    FINDENT NUMBER(6) NOT NULL,  -- 들여쓰기 
    FIP VARCHAR2(50) NOT NULL,  -- ip
    FFILENAME1 VARCHAR2(100),
    FFILENAME2 VARCHAR2(100),
    FFILENAME3 VARCHAR2(100)
);

INSERT INTO FREEBOARD (FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES (FREE_SEQ.NEXTVAL, 'aaa', '제목1', '본문~1', FREE_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );
INSERT INTO FREEBOARD (FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES (FREE_SEQ.NEXTVAL, 'aaa', '제목2', '본문~2', FREE_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );
INSERT INTO FREEBOARD (FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES (FREE_SEQ.NEXTVAL, 'aaa', '제목3', '본문~3', FREE_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );
INSERT INTO FREEBOARD (FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES (FREE_SEQ.NEXTVAL, 'aaa', '제목4', '본문~4', FREE_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );
INSERT INTO FREEBOARD (FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES (FREE_SEQ.NEXTVAL, 'aaa', '제목5', '본문~5', FREE_SEQ.CURRVAL, 0, 0, '192.168.10.30', 'yaho.jpg', 'yaho2.jpg', NULL );

-- 글 목록 ( startRow ~ endRow )
SELECT FB.*, MNAME FROM 
    (SELECT ROWNUM RN, A.* FROM (SELECT * FROM FREEBOARD ORDER BY FGROUP DESC, FSTEP ) A ) FB, MEMBER M
        WHERE FB.MID = M.MID
         AND RN BETWEEN 1 AND 10;
        
-- 전체 글 개수
SELECT COUNT(*) FROM FREEBOARD;


-- 원글 쓰기 
INSERT INTO FREEBOARD( FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES ( FREE_SEQ.NEXTVAL, 'ccc', '동준제목',
                            '동준본문', FREE_SEQ.CURRVAL, 0, 0,
                                    '192.168.10.10', NULL, NULL, NULL ); 
-- FNUM으로 조회수 올리기
UPDATE FREEBOARD SET FHIT = FHIT + 1
    WHERE FNUM = 2;
    
-- 글 상세보기 ( FNUM으로 DTO 가져오기 )
SELECT FB.*, MNAME FROM FREEBOARD FB, MEMBER M WHERE FB.MID = M.MID AND  FNUM =1;

-- 답변글 쓰기전 STEP A 
UPDATE FREEBOARD SET FSTEP = FSTEP +1
    WHERE FGROUP=1 AND FSTEP > 0;
    
--  답변글 쓰기
INSERT INTO FREEBOARD(FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES ( FREE_SEQ.NEXTVAL, 'ccc', '답변글-악플1', '야이자식아', 1, 1, 1, '127.0.0.1', NULL, NULL, NULL );
    
UPDATE FREEBOARD SET FSTEP = FSTEP +1
    WHERE FGROUP=1 AND FSTEP > 0;
    
INSERT INTO FREEBOARD(FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES ( FREE_SEQ.NEXTVAL, 'ccc', '답변글-악플2', '야이자식아', 1, 1, 1, '127.0.0.1', NULL, NULL, NULL );
    
UPDATE FREEBOARD SET FSTEP = FSTEP +1
    WHERE FGROUP=1 AND FSTEP > 0;
    
INSERT INTO FREEBOARD(FNUM, MID, FTITLE, FCONTENT, FGROUP, FSTEP, FINDENT, FIP, FFILENAME1, FFILENAME2, FFILENAME3 )
    VALUES ( FREE_SEQ.NEXTVAL, 'ccc', '답변글-악플3', '야이자식아', 1, 1, 1, '127.0.0.1', NULL, NULL, NULL );

-- 글 수정
UPDATE FREEBOARD SET FTITLE = '수정제목1',
                        FCONTENT = '수정 본문1',
                            FIP = '수정 IP',
                                FFILENAME1 = NULL,
                                    FFILENAME2 = NULL,
                                        FFILENAME3 = NULL,
                                            FRDATE = SYSDATE
                            WHERE FNUM=1;
                                            
-- 글 삭제   -- 밑의 글들도 다 삭제됨
DELETE FROM FREEBOARD WHERE FGROUP = ? AND (FSTEP>=? AND     -- 밑의 FGROUP 에는 삭제할 글의 FGROUP
    FSTEP<(SELECT NVL(MIN(FSTEP),9999) FROM FREEBOARD WHERE FGROUP=? AND FSTEP>? AND FINDENT<=?));

COMMIT;
    
    


