DROP TABLE REVIEW;

DROP SEQUENCE REVIEW_SEQ;

CREATE TABLE REVIEW (
    RNUM NUMBER(6) PRIMARY KEY,  -- 글 번호
    MID REFERENCES MEMBER(MID) NOT NULL,  -- 작성자 아이디
    AID REFERENCES ADMIN(AID),
    RTITLE VARCHAR2(100) NOT NULL,   -- 제목
    RCONTENT VARCHAR2(3000) NOT NULL,  -- 본문
    RRDATE DATE DEFAULT SYSDATE NOT NULL,  -- 작성시점 
    RHIT NUMBER(6) DEFAULT 0 NOT NULL,  -- 조회수
    RGROUP NUMBER(6) NOT NULL,   -- 글 그룹
    RSTEP NUMBER(6) NOT NULL,  -- 그룹내 출력 순서
    RINDENT NUMBER(6) NOT NULL,  -- 들여쓰기 
    RIP VARCHAR2(50) NOT NULL,  -- ip
    RFILENAME1 VARCHAR2(100),
    RFILENAME2 VARCHAR2(100),
    RFILENAME3 VARCHAR2(100)
);
SELECT * FROM ADMIN;

CREATE SEQUENCE REVIEW_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT * FROM REVIEW;
-- 후기 게시글 
INSERT INTO REVIEW (RNUM, MID, AID, RTITLE, RCONTENT, RGROUP, RSTEP, RINDENT, RIP, RFILENAME1, RFILENAME2, RFILENAME3 )
    VALUES (REVIEW_SEQ.NEXTVAL, 'aaa','happydog', '제목1', '본문~1', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );


-- 글 목록 ( startRow ~ endRow )
SELECT * FROM 
    (SELECT ROWNUM RN, A.* FROM (SELECT R.*, MNAME FROM REVIEW R, MEMBER M WHERE R.MID= M.MID ORDER BY RGROUP DESC, RSTEP ) A )
          WHERE RN BETWEEN 1 AND 10;
        
-- 전체 글 개수
SELECT COUNT(*) FROM REVIEW;


-- 원글 쓰기 
INSERT INTO REVIEW (RNUM, MID, AID, RTITLE, RCONTENT, RGROUP, RSTEP, RINDENT, RIP, RFILENAME1, RFILENAME2, RFILENAME3 )
    VALUES (REVIEW_SEQ.NEXTVAL, 'aaa','happydog', '제목2', '본문~2', REVIEW_SEQ.CURRVAL, 0, 0, '192.168.10.30', NULL, NULL, NULL );
    
-- FNUM으로 조회수 올리기
UPDATE REVIEW SET RHIT = RHIT + 1
    WHERE RNUM = 1;
    
-- 글 상세보기 ( FNUM으로 DTO 가져오기 )
SELECT R.*, MNAME FROM REVIEW R, MEMBER M WHERE R.MID = M.MID AND  RNUM =1;

-- 답변글 쓰기전 STEP A 
UPDATE REVIEW SET RSTEP = RSTEP +1
    WHERE RGROUP=1 AND RSTEP > 0;
    
--  답변글 쓰기
INSERT INTO REVIEW (RNUM, MID,  RTITLE, RCONTENT, RGROUP, RSTEP, RINDENT, RIP, RFILENAME1, RFILENAME2, RFILENAME3 )
    VALUES (REVIEW_SEQ.NEXTVAL, 'ccc', '1번글-답변글', '본문~1', 1, 1, 1, '127.168.10.30', NULL, NULL, NULL );
    
UPDATE REVIEW SET RSTEP = RSTEP +1
    WHERE RGROUP=1 AND RSTEP > 0;
    
INSERT INTO REVIEW (RNUM, MID,  RTITLE, RCONTENT, RGROUP, RSTEP, RINDENT, RIP, RFILENAME1, RFILENAME2, RFILENAME3 )
    VALUES (REVIEW_SEQ.NEXTVAL, 'ccc', '1번글-답변글', '본문~1', 1, 1, 1, '127.168.10.30', NULL, NULL, NULL );
    
UPDATE REVIEW SET RSTEP = RSTEP +1
    WHERE RGROUP=1 AND RSTEP > 0;
    
INSERT INTO REVIEW (RNUM, MID,  RTITLE, RCONTENT, RGROUP, RSTEP, RINDENT, RIP, RFILENAME1, RFILENAME2, RFILENAME3 )
    VALUES (REVIEW_SEQ.NEXTVAL, 'ccc', '1번글-답변글', '본문~1', 1, 1, 1, '127.168.10.30', NULL, NULL, NULL );

-- 글 수정
UPDATE REVIEW SET RTITLE = '수정제목1',
                        RCONTENT = '수정 본문1',
                            RIP = '수정 IP',
                                RFILENAME1 = NULL,
                                    RFILENAME2 = NULL,
                                        RFILENAME3 = NULL,
                                            RRDATE = SYSDATE
                            WHERE RNUM=1;
           
-- 글 삭제   -- 밑의 글들도 다 삭제됨
DELETE FROM REVIEW WHERE RGROUP = ? AND (RSTEP>=? AND     -- 밑의 FGROUP 에는 삭제할 글의 FGROUP
    RSTEP<(SELECT NVL(MIN(RSTEP),9999) FROM REVIEW WHERE RGROUP=? AND RSTEP>? AND RINDENT<=?));
rollback;
COMMIT;    
